(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (powerline spinner alert log4e gntp markdown-mode hydra parent-mode request gitignore-mode marshal flycheck flx magit magit-popup git-commit with-editor smartparens iedit anzu evil goto-chg undo-tree highlight diminish projectile pkg-info epl pos-tip company bind-map bind-key packed helm avy helm-core async yasnippet s auto-complete popup package-build rainbow-mode rainbow-identifiers prodigy lua-mode ibuffer-projectile engine-mode deft color-identifiers-mode yaml-mode org-octopress orglue epic org blog-admin names ctable company-sourcekit sourcekit dash-functional swift-mode php-eldoc evil-unimpaired org-projectile mwim github-search semantic-php company-php wgrep uuidgen smex paredit osx-dictionary org-mac-link org-download nodejs-repl lispy link-hint keyfreq ivy-hydra impatient-mode simple-httpd flyspell-correct-ivy flyspell-correct-helm flyspell-correct feature-mode eyebrowse evil-visual-mark-mode evil-ediff etags-select counsel-projectile counsel swiper ivy column-enforce-mode cmake-font-lock ac-php ac-php-core xcscope phpunit f phpcbf php-extras php-auto-yasnippets emacs-eclim drupal-mode php-mode reveal-in-osx-finder ranger pbcopy osx-trash magit-gh-pulls launchctl github-clone github-browse-file git-link gist gh logito pcache disaster company-c-headers cmake-mode clang-format ws-butler window-numbering which-key volatile-highlights vi-tilde-fringe use-package toc-org spacemacs-theme spaceline solarized-theme smooth-scrolling smeargle restart-emacs rainbow-delimiters quelpa popwin persp-mode pcre2el paradox page-break-lines orgit org-repo-todo org-present org-pomodoro org-plus-contrib org-bullets open-junk-file neotree move-text mmm-mode markdown-toc magit-gitflow macrostep lorem-ipsum linum-relative leuven-theme info+ indent-guide ido-vertical-mode hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers highlight-indentation help-fns+ helm-themes helm-swoop helm-projectile helm-mode-manager helm-make helm-gitignore helm-flyspell helm-flx helm-descbinds helm-company helm-c-yasnippet helm-ag google-translate golden-ratio gnuplot gitconfig-mode gitattributes-mode git-timemachine git-messenger gh-md flycheck-pos-tip flx-ido fill-column-indicator fancy-battery expand-region exec-path-from-shell evil-visualstar evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-args evil-anzu eval-sexp-fu elisp-slime-nav define-word company-statistics company-quickhelp clean-aindent-mode buffer-move bracketed-paste auto-yasnippet auto-highlight-symbol auto-dictionary auto-compile aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line ac-ispell))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
